### ISSUE TITLE
So what's this mod about?

### ISSUE THREAD

**Issue by makumaku1974** [vrs2210/iron-age-1.21#1]
I know Iron Age but thinking Minecraft already has iron tools and weapons.

**Comment by vrs2210** [comment]
I haven't added a readme on the GitHub page yet.

The mod adds a branched path of profession starting from iron, which is why I named it iron age.

**Comment by makumaku1974** [comment]
> I haven't added a readme on the GitHub page yet.
> 
> The mod adds a branched path of profession starting from iron, which is why I named it iron age.

Ahh I see but this removes stone and wood tools?

**Comment by makumaku1974** [comment]
If this would be compatible with Bronze Mod. Advancements and tier progression would be cool. Since starting with Iron makes sense removing other tools.

**Comment by vrs2210** [comment]
It doesn't remove any default tools from the game, it's moreso an extension.
A bronze mod would be interesting to implement as a compatability, thanks for the suggestion.

**Comment by makumaku1974** [comment]
I see, I was wishing for a steel to be implemented by the same modder but she had no plans for it though. Bronze is next to steel and clearly a bit strong than iron and bronze. But could you perhaps change tier progression?

**Comment by vrs2210** [comment]
I'll try, before that, could you send me some kind of progression chart that could possibly be better than the one I've currently implemented?

**Comment by makumaku1974** [comment]
I would say since I use a mod called Slow Your Roll which removes wood and stone which is also replaced by flint (wood) and copper (stone)

my headcanon would be: Wood>Stone>Iron>Bronze>Steel>Diamond>Netherite>Mythril>Adamantite

**Comment by vrs2210** [comment]
I see, I may be able to figure something out.
Do note that this new progression style might be under a new mod/mod name, seeing as this mod was built to only be extended off Iron.

**Comment by makumaku1974** [comment]
> I see, I may be able to figure something out. Do note that this new progression style might be under a new mod/mod name, seeing as this mod was built to only be extended off Iron.

Would love to see what you will cook for this mod. Much appreciate for trying out my idea, but it's going to take some time roughly. For the moment, I've got my hands full for animating modded items in other mods.

**Comment by vrs2210** [comment]
Thanks, and I hope it'll go good with the animations you're working on.

**Comment by makumaku1974** [comment]
Btw, I'll try out your mod today if there are bugs or unnecessary things that bugs the game.
